config/routes.rb
Rails.application.routes.draw do
  root to: 'session#show'
  post '/' => 'session#create'
  resources :users, only: [:new, :create]
  resources :messages
  resources :channels
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  has_many :memberships
  has_many :users, dependent: :destroy, through: :memberships
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :channel
  has_many :messages
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :membership
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :memberships
  has_many :channels, dependent: :destroy, through: :memberships
  validates_format_of :email, with: /\A[\w.+\-]+@[\w.+\-]+\.\w+\z/
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionHelper
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  def show
    @user = User.find(params[:id])
    @channels = @user.channels
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    # @messages = Message.find_by(user_id: session[:user_id])
    @messages = Message.all
  end
  # def show
  #   @message = Message.find(params[:id])
  # end
  def new
    @message = Message.new
  end
  def create
    message = Message.create(new_message_params)
    redirect_to messages_path
  end
  def edit
    @message = Message.find(params[:id])
  end
  def update
    message = Message.find(params[:id])
    message.update(message_params)
    redirect_to messages_path
  end
  def destroy
    message = Message.find(params[:id])
    message.destroy
    redirect_to messages_path
  end
  private
  def new_message_params
    message_params.merge(user: current_user)
  end
  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def show
    @users = User.all
  end
  def create
    user = User.find_by(email: params[:email])
    if user
      login user
      redirect_to channel_path(id: user.id)
    else
      render 'show'
      flash[:alert]="You must enter a registered email address."
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to root_path
    else
      render 'new'
    end
  end
  private
  def user_params
    params.require(:user).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def login(user)
    session[:user_id] = user.id
    session[:email] = user.email
  end
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def message_author(message)
    if message.user_id == current_user.try(:id)
      'You'
    else
      message.user.email
    end
  end
  def message_author?(message)
    message.user_id == current_user.try(:id)
  end

end

app/views/channels/show.html.slim
h2 Your channels
- @channels.each do |channel|
  = link_to channel.channelname, channel_path(channel)
  br

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    title Messages - Like Slack

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body

    = yield

app/views/messages/_form.html.slim
= form_for @message do |f|
  = f.label :content, 'Message'
  = f.text_field :content
  = f.submit

app/views/messages/edit.html.slim
h2 Edit Message
= render "form"

app/views/messages/index.html.slim
h2 Messages
= link_to 'New message', new_message_path
- @messages.each do |message|
  h4 = message.content
  | Posted by:
  =< message_author(message)
  br
  - if message_author?(message)
    => link_to 'Edit', edit_message_path(message)
    =< link_to 'Delete', message_path(message), method: :delete

app/views/messages/new.html.slim
h2 New Message
= render "form"

app/views/messages/show.html.slim
h2 = @message.content
| Posted by:
=< link_to message_author(@message), user_path(id: @message.user_id)

app/views/session/show.html.slim
-if flash[:alert]
  h4 Error
  ul
    li = flash[:alert]
h2 Sign in
= form_tag
input type="text" id="email" name="email" placeholder="Email"
br
br
button type="submit" Sign in
br
br
= link_to 'Need a login?', new_user_path
hr
h2 User list
- @users.each do |user|
  = user.email
  br

app/views/users/new.html.slim
-if @user.errors.present?
  h4 Error
  ul
    -for error in @user.errors.full_messages
      li = error
= form_for @user do |f|
  = f.label :email, 'E-mail'
  = f.text_field :email
  = f.submit